set quiet

main := "main.py"

[private]
default:
  just --list --list-heading $'  `euler-py` recipes:\n' --list-prefix "    "

# ---------------------------------------------------------

fix:
  ruff check --fix --unsafe-fixes

fmt:
  ruff format

lint:
  ruff check --unsafe-fixes

solve number:
  #!/usr/bin/env bash
  sol="src/sols/p{{number}}.py"

  if [ ! -f "$sol" ]; then
    echo "$sol doesn't exist!"
    exit 1
  fi

  sed -i "s/p[0-9]\+/p{{number}}/g" {{main}}

  uv run {{main}}
