set quiet

main := "main.py"

[private]
default:
  just --list --list-heading $'  `euler-py` recipes:\n' --list-prefix "    "

# ---------------------------------------------------------

fix:
  ruff check --fix --unsafe-fixes

fmt:
  ruff format

lint:
  ruff check --unsafe-fixes

solve number:
  sed -i "s/p[0-9]\+/p{{number}}/" {{main}}
  uv run {{main}}
