set quiet

cpp := "c++20"
result := "out"

bin := result / "euler"
main := "src/main.cpp"

# ---------------------------------------------------------

[private]
default:
  just --list --list-heading $'  `euler-cpp` recipes:\n' --list-prefix "    "

# ---------------------------------------------------------

init num:
  #!/usr/bin/env bash
  set -euo pipefail

  file="src/sols/p{{num}}.hpp"

  boilerplate="""
  // https://projecteuler.net/problem={{num}}
  // -------------------------------------------------------------------------------------

  #include <chrono>
  #include <cstdint>
  #include <iostream>

  #include \"include/stopwatch.hpp\"

  using namespace std::chrono;

  inline void solve_p{{num}}() {
    auto start = steady_clock::now();

    auto end = steady_clock::now();

    stopwatch(start, end);
  }
  """

  echo "$boilerplate" | sed "1d" > $file
  clang-format -i $file

# ---------------------------------------------------------

compile num:
  #!/usr/bin/env bash

  sol="src/sols/p{{num}}.hpp"

  if [ ! -f "$sol" ]; then
    echo "$sol doesn't exist!"
    exit 1
  fi

  sed -i "s/p[0-9]\+/p{{num}}/g" {{main}}

  mkdir -p {{result}}
  clang++ {{main}} \
          -std={{cpp}} \
          -Iinclude \
          -Isols \
          -Wall \
          -Wextra \
          -o {{bin}}-{{num}}

solve num: (compile num)
  ./{{bin}}-{{num}}
