set quiet

cpp := "c++20"
result := "out"

bin := result / "euler"
main := "src/main.cpp"

[private]
default:
  just --list --list-heading $'  `euler-cpp` recipes:\n' --list-prefix "    "

# ---------------------------------------------------------

compile number:
  #!/usr/bin/env bash
  sol="src/sols/p{{number}}.hpp"

  if [ ! -f "$sol" ]; then
    echo "$sol doesn't exist!"
    exit 1
  fi

  sed -i "s/p[0-9]\+/p{{number}}/g" {{main}}

  mkdir -p {{result}}
  clang++ {{main}} \
          -std={{cpp}} \
          -Iinclude \
          -Isols \
          -Wall \
          -Wextra \
          -o {{bin}}-{{number}}

solve number: (compile number)
  ./{{bin}}-{{number}}
