// https://projecteuler.net/problem=12
// -------------------------------------------------------------------------------------
// The sequence of triangle numbers is generated by adding the natural numbers.
// The formula for the nth triangle number, T-n, is:
//   - n(n + 1)) / 2
// -------------------------------------------------------------------------------------
// Find the first triangle number with over 500 divisors.

use std::collections::HashMap;
use std::time::Instant;

use crate::utils::primes::prime_factors_of;
use crate::utils::stopwatch;

#[inline]
const fn nth_triangle_num(n: u64) -> u64 {
    (n * (n + 1)) / 2
}

#[inline]
fn div_count(n: u64) -> u64 {
    let factors = prime_factors_of(n);

    let mut counts = HashMap::new();

    for prime in factors {
        *counts.entry(prime).or_insert(0) += 1;
    }

    counts.values().map(|exponent| exponent + 1).product()
}

#[allow(clippy::maybe_infinite_iter)]
#[inline]
pub fn solve_p12() {
    const TARGET: u64 = 500;

    let start = Instant::now();

    let answer = (1..)
        .map(nth_triangle_num)
        .find(|&n| div_count(n) >= TARGET)
        .expect("iterator shouldn't be empty!");

    let duration = start.elapsed();

    println!("{answer}");
    stopwatch(duration);
}
